import type { DemoRoute } from './types'

const servicesList = {
  vllm: {
    name: 'vllm',
    display_name: 'vLLM (Qwen2.5-7B-AWQ)',
    is_running: true,
    pid: 1234,
    memory_mb: 6144,
    port: 11434,
    internal: false,
    gpu_required: true,
    cpu_only: false,
    log_file: 'logs/vllm.log',
    last_error: null,
    uptime_seconds: 86400,
  },
  xtts: {
    name: 'xtts',
    display_name: 'XTTS v2 (Voice Clone)',
    is_running: true,
    pid: 1235,
    memory_mb: 5120,
    port: null,
    internal: true,
    gpu_required: true,
    cpu_only: false,
    log_file: 'logs/xtts.log',
    last_error: null,
    uptime_seconds: 86400,
  },
  piper: {
    name: 'piper',
    display_name: 'Piper TTS (CPU)',
    is_running: true,
    pid: 1236,
    memory_mb: 256,
    port: null,
    internal: true,
    gpu_required: false,
    cpu_only: true,
    log_file: 'logs/piper.log',
    last_error: null,
    uptime_seconds: 86400,
  },
  vosk: {
    name: 'vosk',
    display_name: 'Vosk STT',
    is_running: true,
    pid: 1237,
    memory_mb: 512,
    port: null,
    internal: true,
    gpu_required: false,
    cpu_only: true,
    log_file: 'logs/vosk.log',
    last_error: null,
    uptime_seconds: 86400,
  },
  orchestrator: {
    name: 'orchestrator',
    display_name: 'Orchestrator (FastAPI)',
    is_running: true,
    pid: 1000,
    memory_mb: 384,
    port: 8002,
    internal: false,
    gpu_required: false,
    cpu_only: false,
    log_file: 'logs/orchestrator.log',
    last_error: null,
    uptime_seconds: 172800,
  },
  redis: {
    name: 'redis',
    display_name: 'Redis Cache',
    is_running: false,
    pid: null,
    memory_mb: null,
    port: 6379,
    internal: false,
    gpu_required: false,
    cpu_only: false,
    log_file: null,
    last_error: 'Connection refused',
    uptime_seconds: 0,
  },
}

const logLines = [
  '[2024-01-15 10:00:01] INFO: System started successfully',
  '[2024-01-15 10:00:02] INFO: vLLM backend initialized with Qwen2.5-7B-Instruct-AWQ',
  '[2024-01-15 10:00:03] INFO: XTTS v2 voice clone service ready',
  '[2024-01-15 10:00:04] INFO: Loading voice profiles: gulya, lidia',
  '[2024-01-15 10:00:05] INFO: Piper TTS initialized with dmitri voice',
  '[2024-01-15 10:00:06] INFO: Vosk STT model loaded: vosk-model-ru-0.42',
  '[2024-01-15 10:00:07] INFO: FAQ loaded: 12 entries',
  '[2024-01-15 10:00:08] INFO: Telegram bots auto-started: 2/2',
  '[2024-01-15 10:01:00] INFO: Health check: all services healthy',
  '[2024-01-15 10:05:00] INFO: Request processed in 42ms (LLM: Qwen2.5-7B)',
  '[2024-01-15 10:05:01] INFO: TTS synthesis completed: 2.3s for 45 chars',
  '[2024-01-15 10:10:00] INFO: GPU memory: 11.2/12.0 GB (93% used)',
  '[2024-01-15 10:15:00] INFO: Active sessions: admin=1, telegram=3, widget=1',
  '[2024-01-15 10:20:00] INFO: Cache hit rate: 67% (TTS)',
  '[2024-01-15 10:25:00] INFO: Periodic health check passed',
]

export const servicesRoutes: DemoRoute[] = [
  {
    method: 'GET',
    pattern: /^\/admin\/services\/status$/,
    handler: () => ({
      services: servicesList,
      timestamp: new Date().toISOString(),
    }),
  },
  {
    method: 'POST',
    pattern: /^\/admin\/services\/([^/]+)\/(start|stop|restart)$/,
    handler: ({ matches }) => ({
      status: 'ok',
      message: `Service ${matches[1]} ${matches[2]}ed successfully`,
      pid: 1240,
    }),
  },
  {
    method: 'POST',
    pattern: /^\/admin\/services\/(start-all|stop-all)$/,
    handler: ({ matches }) => ({
      status: 'ok',
      results: Object.fromEntries(
        Object.keys(servicesList).map(k => [k, { status: 'ok' }])
      ),
    }),
  },
  {
    method: 'GET',
    pattern: /^\/admin\/logs$/,
    handler: () => ({
      logs: [
        { name: 'orchestrator', file: 'orchestrator.log', display_name: 'Orchestrator', size_kb: 245, modified: new Date().toISOString() },
        { name: 'vllm', file: 'vllm.log', display_name: 'vLLM', size_kb: 1024, modified: new Date().toISOString() },
        { name: 'xtts', file: 'xtts.log', display_name: 'XTTS', size_kb: 512, modified: new Date().toISOString() },
      ],
    }),
  },
  {
    method: 'GET',
    pattern: /^\/admin\/logs\/([^/?]+)/,
    handler: () => ({
      lines: logLines,
      total_lines: logLines.length,
      file: 'orchestrator.log',
      start_line: 0,
      end_line: logLines.length,
    }),
  },
]
